import {
  Patient,
  HealthcareFacility,
  HealthcareProvider,
  MedicalDocument,
  MedicalEvent,
  Diagnosis,
  Medication,
  LabResult,
  SourceReference,
  MedicalContradiction,
} from '../../types/medical';

export const SEED_PATIENTS: Patient[] = [
  {
    id: 'pat-john-doe-01',
    name: 'John Doe',
    dateOfBirth: '1979-05-14',
    gender: 'Male',
    bloodGroup: 'B+',
    allergies: ['Penicillin (Documented 2018)', 'Sulfa drugs (Mild)'],
    createdAt: '2018-04-12T09:00:00Z',
    updatedAt: '2026-09-13T10:00:00Z',
  },
  {
    id: 'pat-sarah-chen-02',
    name: 'Sarah Chen',
    dateOfBirth: '1986-11-22',
    gender: 'Female',
    bloodGroup: 'O+',
    allergies: ['No known drug allergies (NKDA)'],
    createdAt: '2021-02-15T11:30:00Z',
    updatedAt: '2026-09-08T14:15:00Z',
  },
];

export const SEED_FACILITIES: HealthcareFacility[] = [
  {
    id: 'fac-meridian-01',
    name: 'Meridian Medical Centre',
    type: 'Multi-Specialty Medical Centre',
    address: '420 Health Sciences Blvd, Metro City, CA 90210',
    createdAt: '2017-01-01T00:00:00Z',
  },
  {
    id: 'fac-lakeside-02',
    name: 'Lakeside Diagnostics',
    type: 'Clinical Laboratory & Pathology Center',
    address: '88 Lakeview Parkway, Suite 100, Metro City, CA 90214',
    createdAt: '2017-01-01T00:00:00Z',
  },
  {
    id: 'fac-citycare-03',
    name: 'CityCare Hospital',
    type: 'Tertiary Acute Care Hospital',
    address: '1200 Grand Avenue, Metro City, CA 90201',
    createdAt: '2015-05-01T00:00:00Z',
  },
  {
    id: 'fac-greenvalley-04',
    name: 'Green Valley Specialty Clinic',
    type: 'Endocrine & Primary Care Outpatient Clinic',
    address: '310 Green Valley Road, Suite 210, Metro City, CA 90218',
    createdAt: '2018-03-01T00:00:00Z',
  },
];

export const SEED_PROVIDERS: HealthcareProvider[] = [
  {
    id: 'prov-jenkins-01',
    name: 'Dr. Sarah Jenkins, MD',
    specialization: 'Internal Medicine & Endocrinology',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    createdAt: '2017-06-01T00:00:00Z',
  },
  {
    id: 'prov-torres-02',
    name: 'Dr. Robert Torres, MD, FACC',
    specialization: 'Cardiovascular Medicine',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    createdAt: '2016-09-01T00:00:00Z',
  },
  {
    id: 'prov-vance-03',
    name: 'Dr. Marcus Vance, MD',
    specialization: 'General Medicine & Preventive Health',
    facilityId: 'fac-greenvalley-04',
    facilityName: 'Green Valley Specialty Clinic',
    createdAt: '2018-04-01T00:00:00Z',
  },
  {
    id: 'prov-rostova-04',
    name: 'Dr. Elena Rostova, MD, PhD',
    specialization: 'Clinical Biochemistry & Pathology',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    createdAt: '2017-02-01T00:00:00Z',
  },
];

export const SEED_DOCUMENTS: MedicalDocument[] = [
  {
    id: 'doc-2026-demo',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2026_demo.pdf',
    documentType: 'Consultation Note',
    documentDate: '2026-09-10',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Uploaded',
    pageCount: 2,
    fileSizeBytes: 218000,
    extractedTextSnippet: 'Outpatient consultation note: Type 2 Diabetes review, Metformin 500 mg twice daily, HbA1c 6.8%, Penicillin allergy (rash documented). Ready for AI extraction.',
    createdAt: '2026-09-10T09:30:00Z',
  },
  {
    id: 'doc-2018-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2018.pdf',
    documentType: 'Consultation Note',
    documentDate: '2018-05-10',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Processed',
    pageCount: 3,
    fileSizeBytes: 245000,
    extractedTextSnippet: 'Patient presents with persistent polyuria, mild fatigue, and polydipsia. Known allergy: Penicillin. Diagnosis confirmed: Type 2 Diabetes Mellitus.',
    createdAt: '2018-05-10T11:00:00Z',
  },
  {
    id: 'doc-2018-rx',
    patientId: 'pat-john-doe-01',
    fileName: 'prescription_2018.pdf',
    documentType: 'Prescription',
    documentDate: '2018-05-10',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Processed',
    pageCount: 1,
    fileSizeBytes: 120000,
    extractedTextSnippet: 'Rx: Metformin HCl 500mg PO once daily with evening meal. Refill: x5.',
    createdAt: '2018-05-10T11:30:00Z',
  },
  {
    id: 'doc-2018-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2018.pdf',
    documentType: 'Lab Report',
    documentDate: '2018-05-08',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 185000,
    extractedTextSnippet: 'Hemoglobin A1c: 6.4 %. Fasting Plasma Glucose: 134 mg/dL. Baseline metabolic panel within normal limits.',
    createdAt: '2018-05-08T15:00:00Z',
  },
  {
    id: 'doc-2019-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2019.pdf',
    documentType: 'Consultation Note',
    documentDate: '2019-06-14',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 210000,
    extractedTextSnippet: 'Annual diabetes surveillance. Patient reports good tolerance to Metformin 500 mg. Blood pressure slightly elevated at 134/86.',
    createdAt: '2019-06-14T10:15:00Z',
  },
  {
    id: 'doc-2019-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2019.pdf',
    documentType: 'Lab Report',
    documentDate: '2019-06-11',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 195000,
    extractedTextSnippet: 'Hemoglobin A1c: 6.6 %. Fasting Blood Glucose: 138 mg/dL. Microalbumin/Creatinine ratio: Normal.',
    createdAt: '2019-06-11T14:30:00Z',
  },
  {
    id: 'doc-2020-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2020.pdf',
    documentType: 'Consultation Note',
    documentDate: '2020-09-22',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    status: 'Processed',
    pageCount: 3,
    fileSizeBytes: 310000,
    extractedTextSnippet: 'Cardiology evaluation for persistent Stage 1 Essential Hypertension. Office BP 146/92 mmHg confirmed on repeat. Initiating Amlodipine.',
    createdAt: '2020-09-22T09:45:00Z',
  },
  {
    id: 'doc-2020-rx',
    patientId: 'pat-john-doe-01',
    fileName: 'prescription_2020.pdf',
    documentType: 'Prescription',
    documentDate: '2020-09-22',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    status: 'Processed',
    pageCount: 1,
    fileSizeBytes: 115000,
    extractedTextSnippet: 'Rx: Amlodipine Besylate 5mg PO daily in the morning. Disp: 90 tablets.',
    createdAt: '2020-09-22T10:00:00Z',
  },
  {
    id: 'doc-2021-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2021.pdf',
    documentType: 'Consultation Note',
    documentDate: '2021-10-18',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 225000,
    extractedTextSnippet: 'Glycemic control trending higher with HbA1c 7.1%. Increased work stress reported. Titrating Metformin to 850mg.',
    createdAt: '2021-10-18T14:00:00Z',
  },
  {
    id: 'doc-2021-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2021.pdf',
    documentType: 'Lab Report',
    documentDate: '2021-10-15',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 198000,
    extractedTextSnippet: 'Hemoglobin A1c: 7.1 %. Total Cholesterol: 204 mg/dL. Triglycerides: 182 mg/dL.',
    createdAt: '2021-10-15T11:00:00Z',
  },
  {
    id: 'doc-2022-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2022.pdf',
    documentType: 'Consultation Note',
    documentDate: '2022-11-05',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    status: 'Processed',
    pageCount: 3,
    fileSizeBytes: 290000,
    extractedTextSnippet: 'Cardiovascular risk stratification and medication adjustment. Blood pressure well controlled on Amlodipine (124/80 mmHg).',
    createdAt: '2022-11-05T13:30:00Z',
  },
  {
    id: 'doc-2022-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2022.pdf',
    documentType: 'Lab Report',
    documentDate: '2022-11-02',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 3,
    fileSizeBytes: 230000,
    extractedTextSnippet: 'Hemoglobin A1c: 7.6 %. LDL Cholesterol: 116 mg/dL. HDL Cholesterol: 44 mg/dL. eGFR: 92 mL/min.',
    createdAt: '2022-11-02T16:00:00Z',
  },
  {
    id: 'doc-2023-discharge',
    patientId: 'pat-john-doe-01',
    fileName: 'discharge_summary_2023.pdf',
    documentType: 'Discharge Summary',
    documentDate: '2023-11-17',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    status: 'Processed',
    pageCount: 5,
    fileSizeBytes: 540000,
    extractedTextSnippet: 'Admission: 2023-11-14. Discharge: 2023-11-17. Admitted for acute symptomatic hyperglycemic decompensation. Allergies on intake record: No Known Drug Allergies (NKDA). Discharge medications: Metformin 1000mg BID, Glimepiride 1mg daily, Amlodipine 5mg daily.',
    createdAt: '2023-11-17T15:30:00Z',
  },
  {
    id: 'doc-2023-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2023.pdf',
    documentType: 'Lab Report',
    documentDate: '2023-11-14',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 4,
    fileSizeBytes: 380000,
    extractedTextSnippet: 'Inpatient admission bloodwork. Hemoglobin A1c: 8.0 %. Random Blood Sugar: 265 mg/dL. Serum Creatinine: 1.05 mg/dL. Serum Sodium: 138 mmol/L.',
    createdAt: '2023-11-14T20:15:00Z',
  },
  {
    id: 'doc-2024-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_2024.pdf',
    documentType: 'Consultation Note',
    documentDate: '2024-07-19',
    facilityId: 'fac-greenvalley-04',
    facilityName: 'Green Valley Specialty Clinic',
    providerId: 'prov-vance-03',
    providerName: 'Dr. Marcus Vance, MD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 215000,
    extractedTextSnippet: 'Post-hospitalization stabilization review. Patient reports occasional late afternoon shakiness on Glimepiride. Glycemic parameters improving.',
    createdAt: '2024-07-19T10:00:00Z',
  },
  {
    id: 'doc-2024-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2024.pdf',
    documentType: 'Lab Report',
    documentDate: '2024-07-16',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 2,
    fileSizeBytes: 205000,
    extractedTextSnippet: 'Hemoglobin A1c: 7.5 %. Fasting Blood Glucose: 148 mg/dL. Lipid Profile: LDL 108 mg/dL, HDL 46 mg/dL, Triglycerides 155 mg/dL.',
    createdAt: '2024-07-16T12:00:00Z',
  },
  {
    id: 'doc-2025-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'specialist_consultation_2025.pdf',
    documentType: 'Consultation Note',
    documentDate: '2025-03-10',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Processed',
    pageCount: 3,
    fileSizeBytes: 320000,
    extractedTextSnippet: 'Comprehensive endocrine consultation. Discontinuing Glimepiride due to mild hypoglycemia episodes. Adding SGLT2 inhibitor Empagliflozin (Jardiance) 10mg daily.',
    createdAt: '2025-03-10T11:45:00Z',
  },
  {
    id: 'doc-2025-rx',
    patientId: 'pat-john-doe-01',
    fileName: 'prescription_2025.pdf',
    documentType: 'Prescription',
    documentDate: '2025-03-10',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Processed',
    pageCount: 1,
    fileSizeBytes: 130000,
    extractedTextSnippet: 'Rx: Empagliflozin (Jardiance) 10mg PO once daily in the morning. Metformin 500mg ER BID. Disp: 90 days.',
    createdAt: '2025-03-10T12:00:00Z',
  },
  {
    id: 'doc-2026-consult',
    patientId: 'pat-john-doe-01',
    fileName: 'consultation_note_2026.pdf',
    documentType: 'Consultation Note',
    documentDate: '2026-08-28',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    status: 'Needs Review',
    pageCount: 3,
    fileSizeBytes: 310000,
    extractedTextSnippet: 'Routine 6-month diabetic & hypertensive review. Excellent compliance. HbA1c at target of 6.8%. Blood pressure optimal at 122/78 mmHg. Continue current regimen.',
    createdAt: '2026-08-28T14:30:00Z',
  },
  {
    id: 'doc-2026-imaging',
    patientId: 'pat-john-doe-01',
    fileName: 'lumbar_spine_xray_2026.pdf',
    documentType: 'Imaging Report',
    documentDate: '2026-09-02',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    status: 'Processing',
    pageCount: 2,
    fileSizeBytes: 420000,
    extractedTextSnippet: 'Radiographic evaluation of lumbar spine. Mild degenerative disc changes at L4-L5 without acute fracture or spondylolisthesis.',
    createdAt: '2026-09-02T11:15:00Z',
  },
  {
    id: 'doc-2026-lab',
    patientId: 'pat-john-doe-01',
    fileName: 'lab_report_2026.pdf',
    documentType: 'Lab Report',
    documentDate: '2026-08-24',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    status: 'Processed',
    pageCount: 3,
    fileSizeBytes: 240000,
    extractedTextSnippet: 'Hemoglobin A1c: 6.8 %. Fasting Plasma Glucose: 118 mg/dL. Total Cholesterol: 168 mg/dL. LDL: 94 mg/dL. HDL: 48 mg/dL. Triglycerides: 130 mg/dL.',
    createdAt: '2026-08-24T16:00:00Z',
  },
];

export const SEED_SOURCE_REFERENCES: SourceReference[] = [
  {
    id: 'src-ref-01',
    documentId: 'doc-2018-consult',
    documentFileName: 'consultation_2018.pdf',
    pageNumber: 1,
    sourceText: 'Allergies: Penicillin (Childhood history of widespread maculopapular rash requiring antihistamines).',
    createdAt: '2018-05-10T11:00:00Z',
  },
  {
    id: 'src-ref-02',
    documentId: 'doc-2018-consult',
    documentFileName: 'consultation_2018.pdf',
    pageNumber: 2,
    sourceText: 'Assessment & Plan: Type 2 Diabetes Mellitus without acute complications. Initiating oral biguanide therapy.',
    createdAt: '2018-05-10T11:00:00Z',
  },
  {
    id: 'src-ref-03',
    documentId: 'doc-2018-lab',
    documentFileName: 'lab_report_2018.pdf',
    pageNumber: 1,
    sourceText: 'Hemoglobin A1c (HbA1c): 6.4 % [Reference Range: 4.0 - 5.6 %]. Fasting Glucose: 134 mg/dL.',
    createdAt: '2018-05-08T15:00:00Z',
  },
  {
    id: 'src-ref-04',
    documentId: 'doc-2019-lab',
    documentFileName: 'lab_report_2019.pdf',
    pageNumber: 1,
    sourceText: 'Hemoglobin A1c (HbA1c): 6.6 % [Reference Range: 4.0 - 5.6 %].',
    createdAt: '2019-06-11T14:30:00Z',
  },
  {
    id: 'src-ref-05',
    documentId: 'doc-2020-consult',
    documentFileName: 'consultation_2020.pdf',
    pageNumber: 1,
    sourceText: 'Vital Signs: BP 146/92 mmHg right arm seated. Assessment: Essential Hypertension, Stage 1.',
    createdAt: '2020-09-22T09:45:00Z',
  },
  {
    id: 'src-ref-06',
    documentId: 'doc-2021-lab',
    documentFileName: 'lab_report_2021.pdf',
    pageNumber: 1,
    sourceText: 'Hemoglobin A1c (HbA1c): 7.1 % [Reference Range: 4.0 - 5.6 %]. Action suggested: review glycemic regimen.',
    createdAt: '2021-10-15T11:00:00Z',
  },
  {
    id: 'src-ref-07',
    documentId: 'doc-2022-lab',
    documentFileName: 'lab_report_2022.pdf',
    pageNumber: 1,
    sourceText: 'Hemoglobin A1c (HbA1c): 7.6 % [Reference Range: 4.0 - 5.6 %]. LDL-C: 116 mg/dL.',
    createdAt: '2022-11-02T16:00:00Z',
  },
  {
    id: 'src-ref-08',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    pageNumber: 1,
    sourceText: 'Emergency Department Intake Summary · Allergies: No Known Drug Allergies (NKDA).',
    createdAt: '2023-11-17T15:30:00Z',
  },
  {
    id: 'src-ref-09',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    pageNumber: 3,
    sourceText: 'Discharge Medications: 1. Metformin 1000mg PO BID with meals. 2. Glimepiride 1mg PO daily. 3. Amlodipine 5mg PO daily.',
    createdAt: '2023-11-17T15:30:00Z',
  },
  {
    id: 'src-ref-10',
    documentId: 'doc-2023-lab',
    documentFileName: 'lab_report_2023.pdf',
    pageNumber: 1,
    sourceText: 'Inpatient Bloodwork: Hemoglobin A1c: 8.0 % [Elevated]. Serum Glucose: 218 mg/dL.',
    createdAt: '2023-11-14T20:15:00Z',
  },
  {
    id: 'src-ref-11',
    documentId: 'doc-2024-lab',
    documentFileName: 'lab_report_2024.pdf',
    pageNumber: 1,
    sourceText: 'Hemoglobin A1c: 7.5 %. Lipid Panel: Total 188 mg/dL, LDL 108 mg/dL, HDL 46 mg/dL, Triglycerides 155 mg/dL.',
    createdAt: '2024-07-16T12:00:00Z',
  },
  {
    id: 'src-ref-12',
    documentId: 'doc-2025-consult',
    documentFileName: 'specialist_consultation_2025.pdf',
    pageNumber: 2,
    sourceText: 'Endocrine Plan: Discontinue Glimepiride due to recurrent hypoglycemic symptoms. Initiate Empagliflozin (Jardiance) 10mg daily.',
    createdAt: '2025-03-10T11:45:00Z',
  },
  {
    id: 'src-ref-13',
    documentId: 'doc-2026-lab',
    documentFileName: 'lab_report_2026.pdf',
    pageNumber: 1,
    sourceText: 'Hemoglobin A1c: 6.8 % [Target Achieved < 7.0 %]. Fasting Glucose: 118 mg/dL. Lipid Profile: LDL 94 mg/dL.',
    createdAt: '2026-08-24T16:00:00Z',
  },
];

export const SEED_CONTRADICTIONS: MedicalContradiction[] = [
  {
    id: 'contra-01',
    patientId: 'pat-john-doe-01',
    category: 'Allergy',
    title: 'Discrepancy in Documented Penicillin Allergy',
    description:
      'A critical documentation mismatch exists between outpatient consultation records documenting a childhood Penicillin allergy with rash and emergency hospital admission records documenting No Known Drug Allergies (NKDA).',
    clinicalExplanation:
      'These records contain conflicting allergy information. One record documents a childhood Penicillin allergy with maculopapular rash, while another clinical record explicitly asserts "No Known Drug Allergies (NKDA)". Review the source records to determine the current, accurate allergy status. No automatic clinical conclusion has been made.',
    severity: 'High',
    status: 'Unreviewed',
    reviewStatus: 'Unreviewed',
    firstFact: 'No Known Drug Allergies (NKDA)',
    secondFact: 'Penicillin Allergy (Childhood history of widespread maculopapular rash)',
    firstDate: '2023-11-17',
    secondDate: '2018-05-10',
    firstProvider: 'Dr. Robert Torres, MD, FACC',
    secondProvider: 'Dr. Sarah Jenkins, MD',
    firstFacility: 'CityCare Hospital',
    secondFacility: 'Meridian Medical Centre',
    firstSourceReference:
      'Emergency Department Intake Summary · Allergies: No Known Drug Allergies (NKDA).',
    secondSourceReference:
      'Allergies: Penicillin (Childhood history of widespread maculopapular rash requiring antihistamines).',
    firstDocument: {
      documentId: 'doc-2023-discharge',
      documentFileName: 'discharge_summary_2023.pdf',
      documentDate: '2023-11-17',
      facilityName: 'CityCare Hospital',
      providerName: 'Dr. Robert Torres, MD, FACC',
      pageNumber: 1,
      quote: 'Emergency Department Intake Summary · Allergies: No Known Drug Allergies (NKDA).',
      fact: 'No Known Drug Allergies (NKDA)',
      sourceReferenceId: 'src-ref-08',
      eventId: 'evt-2023-01',
    },
    secondDocument: {
      documentId: 'doc-2018-consult',
      documentFileName: 'consultation_2018.pdf',
      documentDate: '2018-05-10',
      facilityName: 'Meridian Medical Centre',
      providerName: 'Dr. Sarah Jenkins, MD',
      pageNumber: 1,
      quote: 'Allergies: Penicillin (Childhood history of widespread maculopapular rash requiring antihistamines).',
      fact: 'Penicillin — Childhood maculopapular rash requiring antihistamines',
      sourceReferenceId: 'src-ref-01',
      eventId: 'evt-2018-02',
    },
    sourceA: {
      documentId: 'doc-2018-consult',
      documentFileName: 'consultation_2018.pdf',
      documentDate: '2018-05-10',
      pageNumber: 1,
      quote: 'Allergies: Penicillin (Childhood history of widespread maculopapular rash requiring antihistamines).',
      facilityName: 'Meridian Medical Centre',
      providerName: 'Dr. Sarah Jenkins, MD',
    },
    sourceB: {
      documentId: 'doc-2023-discharge',
      documentFileName: 'discharge_summary_2023.pdf',
      documentDate: '2023-11-17',
      pageNumber: 1,
      quote: 'Emergency Department Intake Summary · Allergies: No Known Drug Allergies (NKDA).',
      facilityName: 'CityCare Hospital',
      providerName: 'Dr. Robert Torres, MD, FACC',
    },
  },
];

export const SEED_DIAGNOSES: Diagnosis[] = [
  {
    id: 'diag-t2d-01',
    patientId: 'pat-john-doe-01',
    name: 'Type 2 Diabetes Mellitus',
    status: 'Active',
    firstDocumentedDate: '2018-05-10',
    lastDocumentedDate: '2026-08-28',
    eventId: 'evt-2018-02',
    documentId: 'doc-2018-consult',
    documentFileName: 'consultation_2018.pdf',
    clinicalNotes: 'Under routine monitoring; current HbA1c 6.8% under dual therapy with Metformin and Empagliflozin.',
    category: 'Endocrine & Metabolic',
    sourceReferenceId: 'src-ref-02',
  },
  {
    id: 'diag-htn-02',
    patientId: 'pat-john-doe-01',
    name: 'Essential Hypertension',
    status: 'Active',
    firstDocumentedDate: '2020-09-22',
    lastDocumentedDate: '2026-08-28',
    eventId: 'evt-2020-02',
    documentId: 'doc-2020-consult',
    documentFileName: 'consultation_2020.pdf',
    clinicalNotes: 'Well-controlled on Amlodipine 5mg daily. Average ambulatory blood pressure 122/78 mmHg.',
    category: 'Cardiovascular',
    sourceReferenceId: 'src-ref-05',
  },
  {
    id: 'diag-dyslipid-03',
    patientId: 'pat-john-doe-01',
    name: 'Hyperlipidemia',
    status: 'Active',
    firstDocumentedDate: '2021-10-15',
    lastDocumentedDate: '2026-08-24',
    eventId: 'evt-2021-02',
    documentId: 'doc-2021-lab',
    documentFileName: 'lab_report_2021.pdf',
    clinicalNotes: 'Managed through lifestyle modifications and cardiovascular surveillance. Recent LDL 94 mg/dL.',
    category: 'Metabolic & Cardiovascular',
  },
  {
    id: 'diag-hyperglyc-04',
    patientId: 'pat-john-doe-01',
    name: 'Acute Hyperglycemic Decompensation',
    status: 'Resolved',
    firstDocumentedDate: '2023-11-14',
    lastDocumentedDate: '2023-11-17',
    eventId: 'evt-2023-01',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    clinicalNotes: 'Triggered during acute respiratory illness and job stress; resolved with IV hydration and therapy intensification.',
    category: 'Acute Inpatient Episode',
    sourceReferenceId: 'src-ref-10',
  },
];

export const SEED_MEDICATIONS: Medication[] = [
  // Current active medications
  {
    id: 'med-metformin-01',
    patientId: 'pat-john-doe-01',
    name: 'Metformin',
    genericName: 'Metformin Hydrochloride (Extended Release)',
    dosage: '500 mg',
    frequency: 'Twice daily with meals',
    route: 'Oral Tablet',
    startDate: '2018-05-10',
    status: 'Active',
    eventId: 'evt-2018-03',
    documentId: 'doc-2018-rx',
    documentFileName: 'prescription_2018.pdf',
    prescribedBy: 'Dr. Sarah Jenkins, MD',
    indication: 'Type 2 Diabetes Mellitus',
    refillNote: 'Active · Refill by Nov 2026',
    sourceReferenceId: 'src-ref-02',
  },
  {
    id: 'med-amlodipine-02',
    patientId: 'pat-john-doe-01',
    name: 'Amlodipine',
    genericName: 'Amlodipine Besylate',
    dosage: '5 mg',
    frequency: 'Once daily in the morning',
    route: 'Oral Tablet',
    startDate: '2020-09-22',
    status: 'Active',
    eventId: 'evt-2020-03',
    documentId: 'doc-2020-rx',
    documentFileName: 'prescription_2020.pdf',
    prescribedBy: 'Dr. Robert Torres, MD',
    indication: 'Essential Hypertension',
    refillNote: 'Active · Refill by Oct 2026',
    sourceReferenceId: 'src-ref-05',
  },
  {
    id: 'med-empagliflozin-03',
    patientId: 'pat-john-doe-01',
    name: 'Empagliflozin',
    genericName: 'Empagliflozin (Jardiance)',
    dosage: '10 mg',
    frequency: 'Once daily in the morning',
    route: 'Oral Tablet',
    startDate: '2025-03-10',
    status: 'Active',
    eventId: 'evt-2025-02',
    documentId: 'doc-2025-rx',
    documentFileName: 'prescription_2025.pdf',
    prescribedBy: 'Dr. Sarah Jenkins, MD',
    indication: 'Type 2 Diabetes & Cardio-renal protection',
    refillNote: 'Active · Refill by Dec 2026',
    sourceReferenceId: 'src-ref-12',
  },

  // Historical / Discontinued medications demonstrating changes over time
  {
    id: 'med-glimepiride-04',
    patientId: 'pat-john-doe-01',
    name: 'Glimepiride',
    genericName: 'Glimepiride',
    dosage: '1 mg',
    frequency: 'Once daily with breakfast',
    route: 'Oral Tablet',
    startDate: '2023-11-17',
    endDate: '2025-03-10',
    status: 'Discontinued',
    eventId: 'evt-2023-03',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    prescribedBy: 'Dr. Robert Torres, MD',
    indication: 'Type 2 Diabetes (Post-discharge intensification)',
    refillNote: 'Discontinued March 2025 due to recurrent hypoglycemic symptoms; replaced with Empagliflozin.',
    sourceReferenceId: 'src-ref-09',
  },
  {
    id: 'med-metformin-titration-05',
    patientId: 'pat-john-doe-01',
    name: 'Metformin (Titrated temporary high dose)',
    genericName: 'Metformin Hydrochloride',
    dosage: '1000 mg',
    frequency: 'Twice daily',
    route: 'Oral Tablet',
    startDate: '2023-11-17',
    endDate: '2025-03-10',
    status: 'Historical',
    eventId: 'evt-2023-03',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    prescribedBy: 'Dr. Robert Torres, MD',
    indication: 'Type 2 Diabetes',
    refillNote: 'Reduced back to 500mg ER BID after addition of SGLT2 inhibitor in 2025.',
  },
];

export const SEED_LAB_RESULTS: LabResult[] = [
  // HbA1c trajectory (2018 - 2026) exactly matching requested pattern:
  // 2018: 6.4, 2019: 6.6, 2021: 7.1, 2022: 7.6, 2023: 8.0, 2024: 7.5, 2026: 6.8
  {
    id: 'lab-a1c-2018',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 6.4,
    unit: '%',
    referenceRange: '< 5.7% (Normal), 5.7 - 6.4% (Prediabetes)',
    testDate: '2018-05-08',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2018-lab',
    documentFileName: 'lab_report_2018.pdf',
    eventId: 'evt-2018-01',
    interpretation: 'Target',
    sourceReferenceId: 'src-ref-03',
  },
  {
    id: 'lab-a1c-2019',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 6.6,
    unit: '%',
    referenceRange: '< 7.0% (Diabetic target)',
    testDate: '2019-06-11',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2019-lab',
    documentFileName: 'lab_report_2019.pdf',
    eventId: 'evt-2019-01',
    interpretation: 'Target',
    sourceReferenceId: 'src-ref-04',
  },
  {
    id: 'lab-a1c-2021',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 7.1,
    unit: '%',
    referenceRange: '< 7.0% (Diabetic target)',
    testDate: '2021-10-15',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2021-lab',
    documentFileName: 'lab_report_2021.pdf',
    eventId: 'evt-2021-01',
    interpretation: 'Elevated',
    sourceReferenceId: 'src-ref-06',
  },
  {
    id: 'lab-a1c-2022',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 7.6,
    unit: '%',
    referenceRange: '< 7.0% (Diabetic target)',
    testDate: '2022-11-02',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2022-lab',
    documentFileName: 'lab_report_2022.pdf',
    eventId: 'evt-2022-01',
    interpretation: 'Elevated',
    sourceReferenceId: 'src-ref-07',
  },
  {
    id: 'lab-a1c-2023',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 8.0,
    unit: '%',
    referenceRange: '< 7.0% (Diabetic target)',
    testDate: '2023-11-14',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    documentId: 'doc-2023-lab',
    documentFileName: 'lab_report_2023.pdf',
    eventId: 'evt-2023-01',
    interpretation: 'Critical',
    sourceReferenceId: 'src-ref-10',
  },
  {
    id: 'lab-a1c-2024',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 7.5,
    unit: '%',
    referenceRange: '< 7.0% (Diabetic target)',
    testDate: '2024-07-16',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2024-lab',
    documentFileName: 'lab_report_2024.pdf',
    eventId: 'evt-2024-01',
    interpretation: 'Elevated',
    sourceReferenceId: 'src-ref-11',
  },
  {
    id: 'lab-a1c-2026',
    patientId: 'pat-john-doe-01',
    testName: 'Hemoglobin A1c (HbA1c)',
    parameterName: 'HbA1c',
    value: 6.8,
    unit: '%',
    referenceRange: '< 7.0% (Diabetic target)',
    testDate: '2026-08-24',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2026-lab',
    documentFileName: 'lab_report_2026.pdf',
    eventId: 'evt-2026-01',
    interpretation: 'Target',
    sourceReferenceId: 'src-ref-13',
  },

  // Supporting tests across the years
  {
    id: 'lab-glucose-2018',
    patientId: 'pat-john-doe-01',
    testName: 'Fasting Plasma Glucose',
    parameterName: 'Fasting Glucose',
    value: 134,
    unit: 'mg/dL',
    referenceRange: '70 - 99 mg/dL',
    testDate: '2018-05-08',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2018-lab',
    documentFileName: 'lab_report_2018.pdf',
    eventId: 'evt-2018-01',
    interpretation: 'Elevated',
  },
  {
    id: 'lab-lipid-ldl-2022',
    patientId: 'pat-john-doe-01',
    testName: 'Lipid Panel',
    parameterName: 'LDL Cholesterol',
    value: 116,
    unit: 'mg/dL',
    referenceRange: '< 100 mg/dL',
    testDate: '2022-11-02',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2022-lab',
    documentFileName: 'lab_report_2022.pdf',
    eventId: 'evt-2022-01',
    interpretation: 'Elevated',
  },
  {
    id: 'lab-glucose-2023',
    patientId: 'pat-john-doe-01',
    testName: 'Serum Glucose (Random/Admission)',
    parameterName: 'Glucose',
    value: 218,
    unit: 'mg/dL',
    referenceRange: '70 - 140 mg/dL',
    testDate: '2023-11-14',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    documentId: 'doc-2023-lab',
    documentFileName: 'lab_report_2023.pdf',
    eventId: 'evt-2023-01',
    interpretation: 'Critical',
  },
  {
    id: 'lab-creat-2023',
    patientId: 'pat-john-doe-01',
    testName: 'Comprehensive Metabolic Panel',
    parameterName: 'Serum Creatinine',
    value: 1.05,
    unit: 'mg/dL',
    referenceRange: '0.74 - 1.35 mg/dL',
    testDate: '2023-11-14',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    documentId: 'doc-2023-lab',
    documentFileName: 'lab_report_2023.pdf',
    eventId: 'evt-2023-01',
    interpretation: 'Normal',
  },
  {
    id: 'lab-lipid-ldl-2026',
    patientId: 'pat-john-doe-01',
    testName: 'Lipid Profile',
    parameterName: 'LDL Cholesterol',
    value: 94,
    unit: 'mg/dL',
    referenceRange: '< 100 mg/dL (Optimal)',
    testDate: '2026-08-24',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2026-lab',
    documentFileName: 'lab_report_2026.pdf',
    eventId: 'evt-2026-01',
    interpretation: 'Normal',
  },
  {
    id: 'lab-lipid-total-2026',
    patientId: 'pat-john-doe-01',
    testName: 'Lipid Profile',
    parameterName: 'Total Cholesterol',
    value: 168,
    unit: 'mg/dL',
    referenceRange: '< 200 mg/dL (Desirable)',
    testDate: '2026-08-24',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2026-lab',
    documentFileName: 'lab_report_2026.pdf',
    eventId: 'evt-2026-01',
    interpretation: 'Normal',
  },
  {
    id: 'lab-lipid-trig-2026',
    patientId: 'pat-john-doe-01',
    testName: 'Lipid Profile',
    parameterName: 'Triglycerides',
    value: 130,
    unit: 'mg/dL',
    referenceRange: '< 150 mg/dL',
    testDate: '2026-08-24',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    documentId: 'doc-2026-lab',
    documentFileName: 'lab_report_2026.pdf',
    eventId: 'evt-2026-01',
    interpretation: 'Normal',
  },
];

export const SEED_MEDICAL_EVENTS: MedicalEvent[] = [
  // 2018
  {
    id: 'evt-2018-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2018-05-08',
    title: 'Baseline Glycemic & Metabolic Labs',
    description: 'Initial venous blood draw. Fasting glucose 134 mg/dL and HbA1c 6.4% confirming early glycemic dysregulation.',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2018-lab',
    documentFileName: 'lab_report_2018.pdf',
    sourceReferenceId: 'src-ref-03',
    createdAt: '2018-05-08T15:00:00Z',
  },
  {
    id: 'evt-2018-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2018-05-10',
    title: 'Initial Internal Medicine Consultation',
    description: 'Evaluation of persistent thirst and polyuria. Type 2 Diabetes documented. Penicillin allergy documented in allergy history.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2018-consult',
    documentFileName: 'consultation_2018.pdf',
    sourceReferenceId: 'src-ref-01',
    createdAt: '2018-05-10T11:00:00Z',
  },
  {
    id: 'evt-2018-03',
    patientId: 'pat-john-doe-01',
    eventType: 'Medication',
    eventDate: '2018-05-10',
    title: 'Metformin Initial Prescription',
    description: 'Prescribed Metformin 500 mg once daily with evening meal to initiate glycemic therapy alongside diet recommendations.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2018-rx',
    documentFileName: 'prescription_2018.pdf',
    sourceReferenceId: 'src-ref-02',
    createdAt: '2018-05-10T11:30:00Z',
  },

  // 2019
  {
    id: 'evt-2019-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2019-06-11',
    title: 'Annual Diabetes Surveillance Bloodwork',
    description: 'HbA1c measured at 6.6%, reflecting stable glycemic response to Metformin monotherapy.',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2019-lab',
    documentFileName: 'lab_report_2019.pdf',
    sourceReferenceId: 'src-ref-04',
    createdAt: '2019-06-11T14:30:00Z',
  },
  {
    id: 'evt-2019-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2019-06-14',
    title: 'Diabetes 1-Year Follow-up',
    description: 'Routine follow-up consultation with Dr. Jenkins. Continued Metformin 500 mg daily. Borderline BP 134/86 noted.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2019-consult',
    documentFileName: 'consultation_2019.pdf',
    createdAt: '2019-06-14T10:15:00Z',
  },

  // 2020
  {
    id: 'evt-2020-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2020-09-22',
    title: 'Cardiovascular Evaluation for Elevated BP',
    description: 'Referred for repeated elevated home blood pressure readings. Office BP 146/92 mmHg confirmed.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    documentId: 'doc-2020-consult',
    documentFileName: 'consultation_2020.pdf',
    sourceReferenceId: 'src-ref-05',
    createdAt: '2020-09-22T09:45:00Z',
  },
  {
    id: 'evt-2020-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Diagnosis',
    eventDate: '2020-09-22',
    title: 'Diagnosis of Essential Hypertension',
    description: 'Stage 1 Essential Hypertension documented in medical record by Dr. Torres.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    documentId: 'doc-2020-consult',
    documentFileName: 'consultation_2020.pdf',
    sourceReferenceId: 'src-ref-05',
    createdAt: '2020-09-22T09:50:00Z',
  },
  {
    id: 'evt-2020-03',
    patientId: 'pat-john-doe-01',
    eventType: 'Medication',
    eventDate: '2020-09-22',
    title: 'Amlodipine Prescription',
    description: 'Commenced Amlodipine 5 mg daily orally to achieve target systolic BP < 130 mmHg.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    documentId: 'doc-2020-rx',
    documentFileName: 'prescription_2020.pdf',
    sourceReferenceId: 'src-ref-05',
    createdAt: '2020-09-22T10:00:00Z',
  },

  // 2021
  {
    id: 'evt-2021-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2021-10-15',
    title: 'Comprehensive Metabolic & Glycemic Labs',
    description: 'HbA1c increased to 7.1%. Total cholesterol 204 mg/dL. Elevated triglyceride levels noted.',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2021-lab',
    documentFileName: 'lab_report_2021.pdf',
    sourceReferenceId: 'src-ref-06',
    createdAt: '2021-10-15T11:00:00Z',
  },
  {
    id: 'evt-2021-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2021-10-18',
    title: 'Diabetes Follow-up & Medication Review',
    description: 'Consultation with Dr. Jenkins. In response to HbA1c 7.1%, Metformin dosage increased to 850 mg daily.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2021-consult',
    documentFileName: 'consultation_2021.pdf',
    createdAt: '2021-10-18T14:00:00Z',
  },

  // 2022
  {
    id: 'evt-2022-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2022-11-02',
    title: 'Lipid Profile & Glycemic Investigations',
    description: 'HbA1c measured at 7.6%. LDL cholesterol 116 mg/dL. Renal indices normal (eGFR 92).',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2022-lab',
    documentFileName: 'lab_report_2022.pdf',
    sourceReferenceId: 'src-ref-07',
    createdAt: '2022-11-02T16:00:00Z',
  },
  {
    id: 'evt-2022-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2022-11-05',
    title: 'Hospital Outpatient Consultation & Medication Adjustment',
    description: 'Outpatient consultation with Dr. Torres at CityCare Hospital. Metformin titrated to 1000 mg daily. Blood pressure stable on Amlodipine.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    documentId: 'doc-2022-consult',
    documentFileName: 'consultation_2022.pdf',
    createdAt: '2022-11-05T13:30:00Z',
  },

  // 2023
  {
    id: 'evt-2023-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Hospitalization',
    eventDate: '2023-11-14',
    title: 'Hospital Admission: Hyperglycemic Decompensation',
    description: 'Emergency admission for marked hyperglycemia (random glucose 265 mg/dL, HbA1c 8.0%). Patient received intravenous fluid rehydration and glycemic stabilization.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    sourceReferenceId: 'src-ref-08',
    createdAt: '2023-11-14T18:00:00Z',
  },
  {
    id: 'evt-2023-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2023-11-14',
    title: 'Inpatient Emergency Metabolic Panel',
    description: 'Admission labs: HbA1c 8.0 %, Glucose 218 mg/dL, Creatinine 1.05 mg/dL, Potassium 4.2 mEq/L.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2023-lab',
    documentFileName: 'lab_report_2023.pdf',
    sourceReferenceId: 'src-ref-10',
    createdAt: '2023-11-14T20:15:00Z',
  },
  {
    id: 'evt-2023-03',
    patientId: 'pat-john-doe-01',
    eventType: 'Medication',
    eventDate: '2023-11-17',
    title: 'Inpatient Discharge Regimen Intensification',
    description: 'Discharged on intensified oral therapy: Metformin 1000 mg twice daily plus Glimepiride 1 mg daily. Amlodipine 5 mg continued.',
    facilityId: 'fac-citycare-03',
    facilityName: 'CityCare Hospital',
    providerId: 'prov-torres-02',
    providerName: 'Dr. Robert Torres, MD, FACC',
    documentId: 'doc-2023-discharge',
    documentFileName: 'discharge_summary_2023.pdf',
    sourceReferenceId: 'src-ref-09',
    createdAt: '2023-11-17T15:30:00Z',
  },

  // 2024
  {
    id: 'evt-2024-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2024-07-16',
    title: 'Comprehensive Follow-up Panel & Lipid Profile',
    description: 'HbA1c improved to 7.5%. Fasting glucose 148 mg/dL. Lipid profile: LDL 108 mg/dL, HDL 46 mg/dL, Triglycerides 155 mg/dL.',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2024-lab',
    documentFileName: 'lab_report_2024.pdf',
    sourceReferenceId: 'src-ref-11',
    createdAt: '2024-07-16T12:00:00Z',
  },
  {
    id: 'evt-2024-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2024-07-19',
    title: 'Post-Hospitalization Primary Care Follow-up',
    description: 'Clinic visit with Dr. Marcus Vance. Discussed occasional afternoon tremulousness related to sulfonylurea (Glimepiride).',
    facilityId: 'fac-greenvalley-04',
    facilityName: 'Green Valley Specialty Clinic',
    providerId: 'prov-vance-03',
    providerName: 'Dr. Marcus Vance, MD',
    documentId: 'doc-2024-consult',
    documentFileName: 'consultation_2024.pdf',
    createdAt: '2024-07-19T10:00:00Z',
  },

  // 2025
  {
    id: 'evt-2025-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2025-03-10',
    title: 'Endocrine Specialist Consultation',
    description: 'Comprehensive review with Dr. Sarah Jenkins. Replaced Glimepiride with SGLT2 inhibitor Empagliflozin to eliminate hypoglycemia risk.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2025-consult',
    documentFileName: 'specialist_consultation_2025.pdf',
    sourceReferenceId: 'src-ref-12',
    createdAt: '2025-03-10T11:45:00Z',
  },
  {
    id: 'evt-2025-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Medication',
    eventDate: '2025-03-10',
    title: 'Empagliflozin (Jardiance) Initiation & Glimepiride Discontinuation',
    description: 'Prescribed Empagliflozin 10 mg once daily. Metformin adjusted to 500 mg ER twice daily. Glimepiride discontinued.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2025-rx',
    documentFileName: 'prescription_2025.pdf',
    sourceReferenceId: 'src-ref-12',
    createdAt: '2025-03-10T12:00:00Z',
  },

  // 2026
  {
    id: 'evt-2026-01',
    patientId: 'pat-john-doe-01',
    eventType: 'Laboratory',
    eventDate: '2026-08-24',
    title: 'Glycemic Target Achievement & Lipid Panel',
    description: 'HbA1c reached clinical target of 6.8%. Fasting glucose 118 mg/dL. Optimal lipid profile with LDL 94 mg/dL.',
    facilityId: 'fac-lakeside-02',
    facilityName: 'Lakeside Diagnostics',
    providerId: 'prov-rostova-04',
    providerName: 'Dr. Elena Rostova, MD, PhD',
    documentId: 'doc-2026-lab',
    documentFileName: 'lab_report_2026.pdf',
    sourceReferenceId: 'src-ref-13',
    createdAt: '2026-08-24T16:00:00Z',
  },
  {
    id: 'evt-2026-02',
    patientId: 'pat-john-doe-01',
    eventType: 'Consultation',
    eventDate: '2026-08-28',
    title: 'Routine 6-Month Review & Therapy Confirmation',
    description: 'Endocrine consultation confirming stable glycemic and blood pressure metrics. Continued current three-medication regimen.',
    facilityId: 'fac-meridian-01',
    facilityName: 'Meridian Medical Centre',
    providerId: 'prov-jenkins-01',
    providerName: 'Dr. Sarah Jenkins, MD',
    documentId: 'doc-2026-consult',
    documentFileName: 'consultation_note_2026.pdf',
    createdAt: '2026-08-28T14:30:00Z',
  },
];
